const regions = [
  'Antarctica',
  'Australia and New Zealand',
  'Baltic Countries',
  'British Isles',
  'Caribbean',
  'Central Africa',
  'Central America',
  'Central and Southeast Europe',
  'Eastern Africa',
  'Eastern Asia',
  'Eastern Europe',
  'Melanesia',
  'Micronesia',
  'Micronesia/Caribbean',
  'Middle East',
  'Nordic Countries',
  'North America',
  'Northern Africa',
  'Polynesia',
  'South America',
  'Southeast Asia',
  'Southern Africa',
  'Southern Europe',
  'Southern and Central Asia',
  'Western Africa',
  'Western Europe'
]

export default regions
