/**
 * JSON-LD Context for GoodTechWiki
 */
module.exports = {
    '@context': {
        //type: '@type',
        type: 'rdf:type',
        //id: '@id',
        '@vocab': 'https://goodtech.wiki/',
        wiki: 'https://goodtech.wiki/',
        rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        Event: { '@id': 'wiki:Event' },
        Organization: { '@id': 'wiki:Organization' },
        Person: { '@id': 'wiki:Person' },
        Product: { '@id': 'wiki:Product' },
        Publication: { '@id': 'wiki:Publication' },
        WorkingGroup: { '@id': 'wiki:WorkingGroup' },
        activities: { '@id': 'wiki:activities', '@container': '@set' },
        annualBudget: { '@id': 'wiki:annualBudget' },
        audience: { '@id': 'wiki:audience' },
        authorsEditors: { '@id': 'wiki:authorsEditors', '@container': '@set' },
        category: { '@id': 'wiki:category', '@container': '@set' },
        date: { '@id': 'wiki:date', '@type': 'Date' },
        dateBegun: { '@id': 'wiki:dateBegun', '@type': 'Date' },
        dateEnded: { '@id': 'wiki:dateEnded', '@type': 'Date' },
        dateFounded: { '@id': 'wiki:dateFounded', '@type': 'Date' },
        digitalHarmsAddressed: { '@id': 'wiki:digitalHarmsAddressed', '@container': '@set' },
        frequency: { '@id': 'wiki:frequency' },
        funding: { '@id': 'wiki:funding' },
        githubProfile: { '@id': 'wiki:githubProfile', '@type': '@id' },
        ipr: { '@id': 'wiki:ipr' },
        jurisdiction: { '@id': 'wiki:jurisdiction' },
        hostOrganization: { '@id': 'wiki:hostOrganization' },
        keyPeople: { '@id': 'wiki:keyPeople', '@container': '@set' },
        license: { '@id': 'wiki:license' },
        linkedinProfile: { '@id': 'wiki:linkedinProfile', '@type': '@id' },
        lisa: { '@id': 'wiki:lisa' },
        locations: { '@id': 'wiki:locations', '@container': '@set' },
        me2bParticipation: { '@id': 'wiki:me2bParticipation' },
        me2bRelationship: { '@id': 'wiki:me2bRelationship' },
        meetingFrequency: { '@id': 'wiki:meetingFrequency' },
        name: { '@id': 'wiki:name' },
        organization: { '@id': 'wiki:organization' },
        organizationType: { '@id': 'wiki:organizationType' },
        parentOrg: { '@id': 'wiki:parentOrg' },
        partners: { '@id': 'wiki:partners', '@container': '@set' },
        people: { '@id': 'wiki:people', '@container': '@set' },
        productsAndOrServices: { '@id': 'wiki:productsAndOrServices' },
        publicationType: { '@id': 'wiki:publicationType' },
        purpose: { '@id': 'wiki:purpose', '@container': '@set' },
        relevantPublications: { '@id': 'wiki:relevantPublications', '@container': '@set' },
        relevantStandards: { '@id': 'wiki:relevantStandards' },
        scope: { '@id': 'wiki:scope' },
        sector: { '@id': 'wiki:sector' },
        sponsoringOrg: { '@id': 'wiki:sponsoringOrg' },
        status: { '@id': 'wiki:status' },
        supportedIdentityTechnologies: { '@id': 'wiki:supportedIdentityTechnologies', '@container': '@set' },
        tags: { '@id': 'wiki:tags', '@container': '@set' },
        techFocus: { '@id': 'wiki:techFocus' },
        termsOfService: { '@id': 'wiki:termsOfService', '@type': '@id' },
        twitterProfile: { '@id': 'wiki:twitterProfile', '@type': '@id' },
        url: { '@id': 'wiki:url', '@type': '@id' },
        uuid: { '@id': 'wiki:uuid' },
        versionOrEdition: { '@id': 'wiki:versionOrEdition' },
        volumeFrequency: { '@id': 'wiki:name' },
        website: { '@id': 'wiki:website', '@type': '@id' },
        workingGroup: { '@id': 'wiki:workingGroup' },
    }
}